# Generated by Django 3.2.15 on 2024-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text="股票代码，如 'AAPL'", max_length=32)),
                ('datatime', models.DateTimeField(auto_now_add=True, help_text='记录日期')),
                ('OPrice', models.DecimalField(decimal_places=4, help_text='开盘价', max_digits=8)),
                ('LPrice', models.DecimalField(decimal_places=4, help_text='最低价', max_digits=8)),
                ('HPrice', models.DecimalField(decimal_places=4, help_text='最高价', max_digits=8)),
                ('CPrice', models.DecimalField(decimal_places=4, help_text='收盘价', max_digits=8)),
            ],
        ),
    ]
